### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Unthred** [RJ/heatmiser-neohub.py#1]
Very new to home assistant so please forgive my stupidity!
I tried out your component a few months ago and I got it working but since then I have had to completely reinstall home assistant and obviously I don't remember anything about it.So I have setup the relevant parts. I cloned your repo as a submodule of my config in custom_components/climate.
Added 
climate:
  platform: heatmiser_neohub
  host: 192.168.13.94
  port: 4242
  debug: True
into my configuration.yaml

So it seems to me from the error its finding the stats
2017-12-20 20:51:28 INFO (MainThread) [custom_components.climate.heatmiser_neohub] Added 0 plugs, 6 stats
2017-12-20 20:51:28 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 399, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 247, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
    attr)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 333, in _attr_setter
    value = getattr(self, name)
  File "/usr/src/app/homeassistant/components/climate/__init__.py", line 736, in supported_features
    raise NotImplementedError()
NotImplementedError

running this in a docker on an UnRaid server
if I exec into the docker and edit the neocli.py to have the ip of my hub and run it with list I get
````
    DEBUG:asyncio:Using selector: EpollSelector
    DEBUG:root:Querying NeoHub for all device data
    <NeoStat id=1  temp=19.6 frost=False name='Kitchen'>
    <NeoStat id=2  temp=16.9 frost=False name='livingroom'>
    <NeoStat id=3  temp=17.3 frost=False name='Office'>
    <NeoStat id=4  temp=15.5 frost=False name='Vestibule'>
   <NeoStat id=6  temp=17.5 frost=False name='Katrin'>
   <NeoStat id=8  temp=19.3 frost=False name='Bedroom'>
````

So it can talk to the hub it seems.

Any ideas? what can I do to debug it more?

Thanks very much

**Comment by RJ** [comment]
Hmm, not sure - it's possible climate components require an extra method or something in newer versions of home assistant. I've not updated my hass version in a while. What version of home assistant are you using?

Hopefully i'll have time in the next couple of weeks to update my install of hass and test it properly.

**Comment by RJ** [comment]
ah just seen your pull request 👍
