### ISSUE TITLE
Error: Unimplemented NeoSomething 

### ISSUE THREAD

**Issue by rosscullen** [RJ/heatmiser-neohub.py#5]
Hi there,

Installed your component on Home Assistant (V 0.87.0) and getting the following message in the log:

WARNING (MainThread) [root] Unimplemented NeoSomething device_type(12)! Only support neostat(1) and neoplug(6) at the mo

My setup is a recently purchased Heatmiser Neohub (gen 2) connected to 6 Neostats (v2) - connected to Heatmiser UH-8.

Would appreciate any suggestions or advise! Thanks

**Comment by rosscullen** [comment]
Have updated to v0.88.1 and now getting something different:

019-02-26 00:02:32 WARNING (MainThread) [homeassistant.loader] You are using a custom component for heatmiser_neohub.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

2019-02-26 00:02:32 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform heatmiser_neohub
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'custom_components.heatmiser_neohub.climate' has no attribute 'setup_platform'

**Comment by rosscullen** [comment]
No response, closing. Using difference module now
